import pytest
from other import clear
from auth import auth_register
from error import InputError, AccessError

def test_valid_user():
    pass

def test_invalid_user();
    pass

